### ISSUE TITLE
Which GPIO pins should SIM PCB 3 wires connect to?

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [sbaresearch/mobile-atlas#3]
Hello,

Its not clear which GPIO pins should SIM PCB 3 wires connect to from the setup docs. It looks like from this [image](https://github.com/sbaresearch/mobile-atlas/blob/main/images/probe_current.jpg) GPIO pins 27,28,29. Is this correct?

**Comment by GGegenhuber** [comment]
Hi,

yes, you are right.

27 = TX (red wire)
28 = RX (black wire)
29 = reset (yellow wire)

![raspberry_pi_pinout](https://github.com/sbaresearch/mobile-atlas/assets/16528957/3db70508-201a-4b80-9338-64746643a8d5)

**Comment by CodeMonkeyKevin** [comment]
Thank you.
