### ISSUE TITLE
The type of Schottky diode used for the SIM adapter PCB?

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [sbaresearch/mobile-atlas#4]
Hello,

Could you please specify specs of Schottky diode (type,size, amps) used on the SIM adapter PCB, 1N5817?

**Comment by GGegenhuber** [comment]
So far we've built two different versions of the SIM Adapter.

For the prototype (non SMD) we've used this BAT 41 STM schottky diode: https://www.reichelt.at/at/de/kleinsignal-schottky-diode-100-v-0-1-a-do-35-bat-41-stm-p219561.html

For the production version (SMD PCB) we've used this BAT41 SOD123 diode: https://www.tme.eu/at/details/bat41zfilm/schottkydioden-smd/stmicroelectronics/

Additionally, we've also built one piece with a regular 1N4148 (SOD123) diode that we had available and it worked equally well. Therefore, I assume it would also work with a 1N5817 diode.
